"""Tests for AGENTS.md sync: template, sanitization, post-skill hook (M3)."""

from __future__ import annotations

import time
from pathlib import Path

import pytest
from mission_ctrl_core.stores import IntentStore
from mission_ctrl_pi.agents_sync import (
    SanitizationError,
    render_agents_md,
    sanitize_field,
    write_agents_md,
)
from mission_ctrl_pi.schemas import AddIdeaInput, InitInput
from mission_ctrl_pi.skills import intent_add_idea, intent_init

CORE_FIXTURES = Path(__file__).resolve().parents[2] / "core" / "tests" / "fixtures"
SNAPSHOTS = Path(__file__).parent / "snapshots"


def _init_store(tmp_path) -> IntentStore:
    store = IntentStore(tmp_path)
    intent_init(
        InitInput(project_name="SyncApp", mission="Synced mission"), store=store
    )
    return store


# ---------------------------------------------------------------------------
# Template + snapshot
# ---------------------------------------------------------------------------


def test_render_contains_expected_sections(tmp_path):
    rendered = render_agents_md(_init_store(tmp_path))
    assert "<!-- Auto-generated by Mission Ctrl. Do not edit manually. -->" in rendered
    assert "Synced mission" in rendered
    assert "## Current Focus" in rendered
    assert "## Backlog Summary" in rendered
    assert "intent:add-idea" in rendered


def test_snapshot_mid_flight():
    store = IntentStore(CORE_FIXTURES / "mid-flight")
    expected = (SNAPSHOTS / "agents_md_mid_flight.md").read_text(encoding="utf-8")
    assert render_agents_md(store) == expected


def test_render_is_deterministic(tmp_path):
    store = _init_store(tmp_path)
    assert render_agents_md(store) == render_agents_md(store)


# ---------------------------------------------------------------------------
# Sanitization
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "value",
    [
        "Nice title <!-- hidden -->",
        "Trailing comment -->",
        "Example ```python print('x')",
        "Multiline\n```js\nalert(1)",
    ],
)
def test_sanitize_field_rejects_injection_vectors(value):
    with pytest.raises(SanitizationError):
        sanitize_field(value)


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("# Heading hijack", "\\# Heading hijack"),
        ("## Sub head", "\\# Sub head"),
        ("[click](http://evil.example)", "\\[click\\](http://evil.example)"),
        ("Use `code` here", "Use \\`code\\` here"),
        ("plain title", "plain title"),
        ("", ""),
        (None, ""),
    ],
)
def test_sanitize_field_escapes_markdown(value, expected):
    assert sanitize_field(value) == expected


def _spec_with_title(store: IntentStore, title: str):
    """Drive add-idea → triage → spec-create so `title` lands in the render."""
    from mission_ctrl_pi.schemas import SpecCreateInput, TriageInput
    from mission_ctrl_pi.skills import intent_spec_create, intent_triage

    add = intent_add_idea(AddIdeaInput(title="Sync feature"), store=store)
    intent_triage(
        TriageInput(idea_id=add.idea_id, bucket="mvp", alignment_verdict="Core"),
        store=store,
    )
    return intent_spec_create(
        SpecCreateInput(idea_id=add.idea_id, title=title), store=store
    )


def test_skill_write_with_injection_title_raises(tmp_path):
    """Post-skill sync rejects injection-attempt titles via SanitizationError."""
    store = _init_store(tmp_path)
    with pytest.raises(SanitizationError):
        _spec_with_title(store, "Feature <!-- inject -->")
    # The spec write itself succeeded; only the post-write sync rejected it.
    assert len(store.specs.read().nodes) == 1


def test_rendered_output_escapes_hostile_titles(tmp_path):
    store = _init_store(tmp_path)
    _spec_with_title(store, "# Not a heading")
    rendered = render_agents_md(store)
    assert "\\# Not a heading" in rendered
    assert "\n# Not a heading" not in rendered


def test_init_with_hostile_mission_escapes(tmp_path):
    store = IntentStore(tmp_path)
    intent_init(
        InitInput(project_name="SyncApp", mission="# Hijack mission"), store=store
    )
    rendered = render_agents_md(store)
    assert "\\# Hijack mission" in rendered


# ---------------------------------------------------------------------------
# Post-skill hook behavior
# ---------------------------------------------------------------------------


def test_init_writes_agents_md_next_to_intent(tmp_path):
    _init_store(tmp_path)
    agents_md = tmp_path / "AGENTS.md"
    assert agents_md.is_file()
    assert "Synced mission" in agents_md.read_text(encoding="utf-8")


def test_skill_write_updates_agents_md(tmp_path):
    store = _init_store(tmp_path)
    agents_md = tmp_path / "AGENTS.md"
    before = agents_md.read_text(encoding="utf-8")
    assert "Untriaged: 0" in before
    intent_add_idea(AddIdeaInput(title="Fresh idea"), store=store)
    after = agents_md.read_text(encoding="utf-8")
    assert "Untriaged: 1" in after
    assert before != after


def test_sync_completes_within_one_second(tmp_path):
    store = _init_store(tmp_path)
    intent_add_idea(AddIdeaInput(title="Timed idea"), store=store)
    start = time.perf_counter()
    write_agents_md(store)
    assert time.perf_counter() - start < 1.0
